apiVersion: apps/v1
kind: Deployment
metadata:
  name: tianlang-app
spec:
  replicas: 1
  # 必须确保留久化标签一致，建议使用 tianlang-web
  selector:
    matchLabels:
      app: tianlang-web
  template:
    metadata:
      labels:
        app: tianlang-web
    spec:
      containers:
      - name: tianlang-app
        # 建议使用 latest 确保拉取你刚推上去的 Nginx 镜像
        image: 192.168.199.142:5000/tianlang-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # --- 注意：删除了之前的 command 和 args，因为 Nginx 镜像会自动启动 ---
---
apiVersion: v1
kind: Service
metadata:
  name: tianlang-svc
spec:
  type: NodePort
  selector:
    app: tianlang-web
  ports:
  - port: 80
    targetPort: 80
    # 老师要求的 NodePort 30088
    nodePort: 30088
