apiVersion: apps/v1
kind: Deployment
metadata:
  name: tianlang-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tianlang-web
  template:
    metadata:
      labels:
        app: tianlang-web
    spec:
      containers:
      - name: tianlang-app
        # ⬇️⬇️⬇️ 关键点：强制使用 54 号镜像 (Python版)
        image: 192.168.199.142:5000/tianlang-app:60
        imagePullPolicy: Always
        # ⬇️⬇️⬇️ 关键点：端口改为 8000
        ports:
        - containerPort: 8000
        env:
          - name: ENV_TYPE
            value: "Production"
          - name: DATABASE_URL
            value: "postgresql://tianlang:securepass@db:5432/weatherdb"
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: tianlang-svc
spec:
  type: NodePort
  selector:
    app: tianlang-web
  ports:
    # --- 关键修改：TargetPort 改为 8000 ---
  - port: 80
    targetPort: 8000
    nodePort: 30088
