apiVersion: apps/v1
kind: Deployment
metadata:
  name: tianlang-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tianlang-web
  template:
    metadata:
      labels:
        app: tianlang-web
    spec:
      containers:
      - name: tianlang-app
        image: 192.168.199.142:5000/tianlang-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tianlang-svc
spec:
  type: NodePort
  selector:
    app: tianlang-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30088
