version: '3.8'

services:
  # 1. 你的应用服务 (Bot + Web + Model)
  app:
    # 这里的 image 会被 Jenkins 替换，但在本地我们可以先写死
    image: tianlang-app:latest 
    restart: always
    ports:
      - "80:8000"  # OpenStack 虚拟机开放 80 端口访问网页
    environment:
      - TELEGRAM_TOKEN=8279271928:AAH3AxAXw6LLdweqgbAOmui9kyaZlr30wn0
      - DATABASE_URL=postgresql://tianlang:securepass@db:5432/weatherdb
    depends_on:
      - db

  # 2. 数据库服务 (Base)
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: tianlang
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: weatherdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
