version: '2.1'

services:
  app:
    image: 192.168.199.142:5000/tianlang-app:latest
    restart: always
    ports:
      - "80:8000"
    environment:
      - TELEGRAM_TOKEN=8279271928:AAH3AxAXw6LLdweqgbAOmui9kyaZlr30wn0
      # ✅ 已经填好你的真实 Key
      - OPENWEATHER_API_KEY=6f1a57419ebc149fac088d8cdc402072
      - DATABASE_URL=postgresql://tianlang:securepass@db:5432/weatherdb
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: tianlang
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: weatherdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: