---
- name: Deploy Weather Bot to OpenStack
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker and Compose
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    # 这一步是为了允许从私有仓库拉取 HTTP 镜像 (防止 HTTPS 报错)
    - name: Configure Docker Insecure Registry
      shell: |
        echo '{"insecure-registries":["192.168.199.142:5000"]}' > /etc/docker/daemon.json
        systemctl restart docker
      ignore_errors: yes

    - name: Create app directory
      file:
        path: /opt/tianlang-app
        state: directory
        mode: '0755'

    - name: Copy project files
      copy:
        src: "{{ item }}"
        dest: /opt/tianlang-app/
      with_items:
        - ../docker-compose.yml
        # 其他文件其实不需要了，因为都在镜像里，但留着也没事

    - name: Stop existing containers
      shell: docker-compose down
      args:
        chdir: /opt/tianlang-app
      ignore_errors: yes

    - name: Pull latest image
      shell: docker-compose pull
      args:
        chdir: /opt/tianlang-app

    - name: Start Application
      shell: docker-compose up -d
      args:
        chdir: /opt/tianlang-app